name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '5.0.x']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version}}
      uses: actions/setup-dotnet@v1.7.2	
      with:	
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload dotnet test eresults
      uses: actions/upload-artifact@v2
      with: 
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-${{ matrix.dotnet-version }}
      if: ${{ always() }}
      
